### ISSUE TITLE
vector_add_um.cu appears "abort() has been called"

### ISSUE THREAD

**Issue by BenoitKAO** [CoffeeBeforeArch/cuda_programming#1]
The environment:
Windows 10
VS 2017
CUDA 10.1

The snapshot of this error:
https://drive.google.com/open?id=1V-Mv2xk9Leny3GEUYsMkBWBHumWastxU

However,
run the same code in Linux environment, there is no error.

Any help is appreciated.

**Comment by CoffeeBeforeArch** [comment]
This is an error with the functional test that compares the CPU-side results with the GPU side. Other than that, I can't tell what would be causing this with the information provided. Either the data is not being copied to/from the GPU properly, or the kernel is not being executed (proof of either of those things would be appreciated for debugging).

My thought is that this is a related to your build with Visual Studio. I would need some more info into how your code is being compiled. One test you could run is to create a new CUDA project in a new directory and copy the code into it. The simple vectorAdd code will not be the problem (as is evident because it works without issue on Linux), so it is likely an issue of interfering Visual Studio files that are in your directory (from VS 2015 and using CUDA 10.0 if you are indeed working in the directory on github, I should probably just remove these) and your environment setup.

**Comment by BenoitKAO** [comment]
Thank you for your reply.
I insert another Nvidia Display Card (newer version) and run source code (vector_add_um.cu) by your tutorials which works perfectly in Windows 10 + VS 2017 + CUDA 10.1. 
The previous Nvidia Display Card (older version) can be run with the ENV: Windows 10 + VS 2015 + cuda 10.0.
Thank you very much~

**Comment by CoffeeBeforeArch** [comment]
Is everything working now? If so, I can go ahead and close the issue. Usually these are build problems related to whether your GPU has SM architecture >= 3.0, and if if you are compiling a 64-bit host application.

**Comment by BenoitKAO** [comment]
Marvelous!
You are really an expert!
The newer version is NVIDIA GeForce RTX 2080 Ti

Please have your help to close this issue.

Thank you very much for helping.
