### ISSUE TITLE
`sumReduction` modification suggestions

### ISSUE THREAD

**Issue by LogWell** [CoffeeBeforeArch/cuda_programming#4]
How do I modify code to accommodate arrays of arbitrary length instead of powers of 2 in `sumReduction`?

**Comment by NicolayP** [comment]
Hi, I'm currently trying to do the same in the reduce Idle version of it: 
I identified two scenarios you need to take care of:
 1. If your array is smaller than ```TB_SIZE * 2```
 2. if the returned array from the first kernel call is bigger than ```TB_SIZE*2```. The returned array is obviously of size ```GRID_SIZE```

In the first case, you only need to call the kernel once as all the threads in one block can cover the entire array.

In the second scenario, you need to call the kernel more than twice. Indeed in opposition to the previous case, one kerne call with a ```GRID_SIZE``` of 1 can cover ```TB_SIZE*2``` array at most so one call will not be enough. Thus you need to adapt the code a bit. You have two options available but I'm only gonna illustrate the one i've done. You can either work with the ```SHMEM_SIZE``` = ```SIZE*4``` and figure all the indexes out. I have quite a limited memory available so I try not to waist it and only initalize ```SHMEM_SIZE``` to ```SIZE``` and use a call to the kernel like this:  ```sum_reduction << <GRID_SIZE, BLOCK_SIZE >> > (d_v_r, d_v_r, n);```. 

Note: i'm using ```d_v_r``` as input and output array. I added ```n``` as an argument to the reduction and it indicates how many elements their are to parse in the input array.

The changed section in the main code looks like this 

```
	// TB Size
	int BLOCK_SIZE = SIZE;

	// Grid Size (cut in half) (No padding)
	int GRID_SIZE = n / BLOCK_SIZE / 2 + 1;


    // insure at least one pass.
    sum_reduction << <GRID_SIZE, BLOCK_SIZE >> > (d_v, d_v_r, n);

    n = GRID_SIZE;
    GRID_SIZE = n / BLOCK_SIZE / 2 + 1 ;
    do
    {
        sum_reduction << <GRID_SIZE, BLOCK_SIZE >> > (d_v_r, d_v_r, n);
        n = GRID_SIZE;
        GRID_SIZE = n / BLOCK_SIZE / 2 + 1 ;
    }
    while (GRID_SIZE - 1 > 1 );
    sum_reduction << <1, BLOCK_SIZE >> > (d_v_r, d_v_r, n);
```

Note: I change ```TB_SIZE``` to ```BLOCK_SIZE``` just because I prefer this term. I added a + 1 to the grid size computation and this takes care of every array with a size different then a power of 2. I know that this will result in 'idle' threads in the last block but I don't know any way around this. 

Finally i modified the sum_reduction first's sum to look like this. 

```
    if (i + blockDim.x < n)
    {
	   partial_sum[threadIdx.x] = v[i] + v[i + blockDim.x];
    }
    else if (i < n)
    {
       partial_sum[threadIdx.x] = v[i];
    }
    else
    {
        partial_sum[threadIdx.x] = 0;
    }
```

This allows me to use my input array as output array because I won't read previously assigned value.

I don't know if this has some very ineffecicient sections and I would be glad to get some feedback about it. Hopes this helps you solve your question :)

**Comment by LogWell** [comment]
I will combine the current answer with another [answer](https://stackoverflow.com/a/27928463/10636347) later, thank you very much~
